server:
  port: 8693

product.host: http://localhost:8688
customer.host: http://localhost:8689
purchase.host: http://localhost:8692

aws:
  region: us-east-1
  sns:
    close-cart:
      name: local-cart-closed-topic