server:
  port: 8693

product.host: http://localhost:8688
customer.host: http://localhost:8689
purchase.host: http://localhost:8692

aws:
  region: us-east-1
  sns:
    close-cart:
      name: local-cart-closed-topic
  sqs:
    manufacture-purchase-created-queue:
      name: local-manufacture-purchase-created-queue
  dynamodb:
    time-to-live: 300

spring:
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1
      dynamodb:
        table-prefix: manufacture_